---
# aws ec2 ansible dynamic inventory plugin
# To install it use: ansible-galaxy collection install amazon.aws
# Reference: https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
plugin: aws_ec2

regions:
  - us-east-1
strict: False

keyed_groups:
  - key: tags
    prefix: tag
  - key: architecture
    prefix: arch
  - key: tags.Applications
    separator: ''
  - key: instance_type
    prefix: aws_instance_type
  - key: placement.region
    prefix: aws_region
  - key: image_id
    prefix: aws_image
  - key: hypervisor
    prefix: aws_hypervisor
  - key: 'security_groups|json_query("[].group_id")'
    prefix: 'security_groups'

hostnames:
  - ip-address
  - dns-name
  - tag:Name
